language: java
before_script:
  - psql -c 'create database alfio;' -U postgres
dist: trusty
sudo: required
install:
    - TERM=dumb ./gradlew -q assemble
matrix:
    include:
        - jdk: oraclejdk8
          env: PROFILE="-Dspring.profiles.active=travis -Ddbenv=PGSQL-TRAVIS -Dpgsql9.6"
          dist: trusty
          addons:
              postgresql: "9.6"

script:
    - TERM=dumb ./gradlew build jacocoTestReport $PROFILE
after_success:
    ./gradlew coveralls
